export {default as Hero} from './hero/Hero'
export {default as Services} from './services/Services'
export {default as Portfolio} from './portfolio/Portfolio'
export {default as Skills} from './skills/Skills'
export {default as Footer} from './footer/Footer'
export {default as Resume} from './resume/Resume'